### ISSUE TITLE
lipnet

### ISSUE THREAD

**Issue by crazygirl1992** [voletiv/lipreading-in-the-wild-experiments#1]
hello, i am a Chinese student weiwei. i also study this direction.    and now i run the lipnet  with grid dataset ,your code is in the wild dataset, can you realize the lip recognation with that dataset?and did you have reported relative papers?

**Comment by voletiv** [comment]
Hi Weiwei, you can use the lipnet on GridCorpus as long as the same procedure is followed to extract the mouth regions. The procedure is given in the README i here - 

https://github.com/voletiv/lipreading-in-the-wild-experiments/tree/master/process-lrw
